"""Shared TypedDict definitions replacing wildcard dict[str, Any] throughout the sidecar.

These types are structural — they document the shape, not enforce it at runtime.
All keys are total=False so downstream code that only reads partial data still type-checks.
"""

from typing import Literal, TypedDict


# ---------------------------------------------------------------------------
# Entity extraction (LLM response shape)
# ---------------------------------------------------------------------------

class CommitmentEntry(TypedDict, total=False):
    owner: str
    what: str
    status: str
    due: str
    source_quote: str


# ``from`` is a reserved keyword, so we use the functional syntax for dicts
# that carry a ``"from"`` key to match the wire format.
RelationEntry = TypedDict("RelationEntry", {
    "from": str,
    "to": str,
    "type": str,
    "evidence": str,
    "confidence": float,
}, total=False)
RelationEntry.__doc__ = """Relation extracted from an interaction.

    The LLM prompt emits ``from`` / ``to`` (the wire format returned to the
    renderer).  ``store_relations()`` also accepts ``from_person`` /
    ``to_person`` as aliases for compatibility.
    """


class UnresolvedEntry(TypedDict, total=False):
    holder: str
    awaiting_from: str
    what: str
    since: str


class ExtractionResult(TypedDict, total=False):
    people: list[str]
    companies: list[str]
    topics: list[str]
    commitments: list[CommitmentEntry]
    relations: list[RelationEntry]
    unresolved: list[UnresolvedEntry]
    stance: str
    sentiment_shift: str | None
    summary: str


# ---------------------------------------------------------------------------
# Canonical stance values (mirrors TS Stance = champion|skeptic|neutral|blocker)
# ---------------------------------------------------------------------------

StanceLiteral = Literal["champion", "skeptic", "neutral", "blocker"]


# ---------------------------------------------------------------------------
# Contact shape (canonical, used across persistence / repo / API)
# ---------------------------------------------------------------------------

class ContactDict(TypedDict, total=False):
    contactEmail: str
    contactName: str
    company: str
    stance: str
    lastInteraction: str
    topics: list[str]
    sentimentShift: str
    commitments: list[CommitmentEntry]
    unresolved: list[UnresolvedEntry]
    summary: str
    interaction_date: str
    topics_raised: list[str]
    extracted: ExtractionResult


# ---------------------------------------------------------------------------
# WebSocket broadcast payloads
# ---------------------------------------------------------------------------

class WSTranscriptMessage(TypedDict):
    type: str  # "transcript"
    text: str


class BriefDict(TypedDict, total=False):
    """Brief data generated by LLM (``brief_generator.py``).

    The LLM is prompted to return these keys.  ``total=False`` because
    LLM output is inherently unreliable — every field is optional at
    the type level.
    """
    contactName: str
    company: str
    currentStance: str
    stanceShiftNote: str
    topConcerns: list[str]
    communicationStyle: str
    talkingPoints: list[str]
    landmines: list[str]
    lastInteraction: str
    powerNote: str
    trigger: str


class WSBriefMessage(TypedDict):
    type: str  # "brief"
    data: dict[str, object]


class WSErrorMessage(TypedDict):
    type: str  # "error"
    message: str


class WSIngestCompleteMessage(TypedDict):
    type: str  # "ingest_complete"
    count: int


WSMessage = WSTranscriptMessage | WSBriefMessage | WSErrorMessage | WSIngestCompleteMessage


# ---------------------------------------------------------------------------
# Calendar meeting
# ---------------------------------------------------------------------------

class MeetingInfo(TypedDict, total=False):
    event_id: str
    summary: str
    contact_email: str
    contact_name: str
    company: str
    start_time: str


# ---------------------------------------------------------------------------
# OpenRouter response
# ---------------------------------------------------------------------------

class OpenRouterChoiceMessage(TypedDict):
    content: str


class OpenRouterChoice(TypedDict):
    message: OpenRouterChoiceMessage


class OpenRouterResponse(TypedDict):
    choices: list[OpenRouterChoice]


# ---------------------------------------------------------------------------
# HydraDB error payload
# ---------------------------------------------------------------------------

class ErrorPayload(TypedDict, total=False):
    status_code: int | None
    error_code: str | None
    message: str


class HydraDBWriteResult(TypedDict, total=False):
    status: str
    transport: str
    data: dict[str, object]
    error: ErrorPayload
    reason: str
    content: str
    metadata: dict[str, object]


class EmailContact(TypedDict, total=False):
    name: str
    email: str
    company: str


EmailItem = TypedDict("EmailItem", {
    "id": str,
    "thread_id": str,
    "subject": str,
    "from": str,
    "to": str,
    "date": str,
    "body": str,
    "contact": "EmailContact",
}, total=False)
EmailItem.__doc__ = """Canonical email shape returned by all readers (IMAP, Gmail, file)."""


# ---------------------------------------------------------------------------
# Graph data  (matches the /graph API response contract)
# ---------------------------------------------------------------------------

class GraphEdgeEvidence(TypedDict, total=False):
    """Evidence backing a single directed edge in the graph."""
    quote: str
    date: str


GraphEdge = TypedDict("GraphEdge", {
    "from": str,
    "to": str,
    "type": str,
    "weight": float,
    "color": str,
    "evidence": list["GraphEdgeEvidence"],
}, total=False)
GraphEdge.__doc__ = """Directed edge in the relationship graph.

    Note: This matches the wire format that ``build_graph()`` returns
    (``from`` / ``to``).  The internal storage format in HydraDB uses
    ``from_person`` / ``to_person`` — the conversion happens in
    ``relationship_graph.store_relations()``.
    """


class GraphNode(TypedDict, total=False):
    id: str
    label: str
    importance: float
    type: str


class GraphData(TypedDict, total=False):
    nodes: list[GraphNode]
    edges: list[GraphEdge]


class DeviceInfo(TypedDict):
    index: int
    name: str
    channels: int
    default_samplerate: float


# ---------------------------------------------------------------------------
# /status endpoint response
# ---------------------------------------------------------------------------

class DepStatusItem(TypedDict, total=False):
    """Mirrors the TS ``DepStatus`` type."""
    ok: bool
    reason: str | None


class SidecarStatusDeps(TypedDict, total=False):
    """Mirrors the TS ``SidecarStatusDeps`` type."""
    hydradb: DepStatusItem
    openrouter: DepStatusItem
    microphone: DepStatusItem
    imap: DepStatusItem


# ---------------------------------------------------------------------------
# /recording/... endpoint responses
# ---------------------------------------------------------------------------

class RecordingStartResult(TypedDict):
    """Mirrors the TS ``RecordingStartResult`` type."""
    status: str  # "recording" | "disabled"
    reason: str | None


# ---------------------------------------------------------------------------
# API response wrappers
# ---------------------------------------------------------------------------

class ContactsResponse(TypedDict, total=False):
    contacts: list[ContactDict]
    source: str
    warning: str
    error: str
